### ISSUE TITLE
readRole breaks if params is null

### ISSUE THREAD

**Issue by gt-c** [cloewen8/Bro-Time-Server#55]
`var variable = call.params.readRole();`
errors when the command is called upon like
`/command`

**Comment by cloewen8** [comment]
Can you please specify which command you were calling and the channel you were calling it in?

**Comment by gt-c** [comment]
this was the issue that broke namecolor and gamerole. I had to verify that the input was not null/undefined by making sure that it was part of the array(s) (for namecolor and gamerole) and simply move the variable inside that if statement

**Comment by gt-c** [comment]
`(node:4108) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at Paramaters.readObject (C:\Users\a\Desktop\Bro-Time-Server-patch-11\Bro-Time-Server-patch-11\server\chat\utility\paramaters.js:62:35)
    at Paramaters.readRole (C:\Users\a\Desktop\Bro-Time-Server-patch-11\Bro-Time-Server-patch-11\server\chat\utility\paramaters.js:96:15)
    at Object.execute (C:\Users\a\Desktop\Bro-Time-Server-patch-11\Bro-Time-Server-patch-11\server\commands\test.js:5:26)
    at Object.exec (C:\Users\a\Desktop\Bro-Time-Server-patch-11\Bro-Time-Server-patch-11\server\chat\commands.js:57:14)
    at task (C:\Users\a\Desktop\Bro-Time-Server-patch-11\Bro-Time-Server-patch-11\server\server.js:59:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:4108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`
exact error

**Comment by cloewen8** [comment]
After further review, this may be related to another bug in which some parameter functions return undefined instead of a valid output, and readObject is not handling this correctly.
